library betting_tennis.globals;

import 'dart:convert';
import 'function.dart';

final List<String> players = [
  'Adrian Mannarino',
  'Albert Ramos',
  'Alejandro Davidovich Fokina',
  'Alex De Minaur',
  'Alex Molcan',
  'Alexander Bublik',
  'Alexander Zverev',
  'Alexandr Dolgopolov',
  'Alexei Popyrin',
  'Aljaz Bedene',
  'Andreas Haider Maurer',
  'Andreas Seppi',
  'Andrej Martin',
  'Andrey Kuznetsov',
  'Andrey Rublev',
  'Andy Murray',
  'Arthur Rinderknech',
  'Aslan Karatsev',
  'Benjamin Becker',
  'Benjamin Bonzi',
  'Benoit Paire',
  'Bernabe Zapata Miralles',
  'Bernard Tomic',
  'Bjorn Fratangelo',
  'Borna Coric',
  'Botic Van De Zandschulp',
  'Brandon Nakashima',
  'Cameron Norrie',
  'Carlos Alcaraz',
  'Carlos Berlocq',
  'Casper Ruud',
  'Christopher Oconnell',
  'Corentin Moutet',
  'Cristian Garin',
  'Damir Dzumhur',
  'Daniel Altmaier',
  'Daniel Elahi Galan',
  'Daniel Evans',
  'Daniil Medvedev',
  'David Ferrer',
  'David Goffin',
  'Denis Istomin',
  'Denis Kudla',
  'Denis Shapovalov',
  'Dennis Novak',
  'Diego Schwartzman',
  'Dominic Thiem',
  'Dominik Koepfer',
  'Donald Young',
  'Dudi Sela',
  'Dusan Lajovic',
  'Dustin Brown',
  'Egor Gerasimov',
  'Elias Ymer',
  'Emil Ruusuvuori',
  'Ernesto Escobedo',
  'Ernests Gulbis',
  'Evgeny Donskoy',
  'Fabio Fognini',
  'Facundo Bagnis',
  'Federico Coria',
  'Federico Delbonis',
  'Feliciano Lopez',
  'Felix Auger Aliassime',
  'Fernando Verdasco',
  'Filip Krajinovic',
  'Florian Mayer',
  'Frances Tiafoe',
  'Francisco Cerundolo',
  'Gael Monfils',
  'Gastao Elias',
  'Gianluca Mager',
  'Gilles Muller',
  'Gilles Simon',
  'Gregoire Barrere',
  'Grigor Dimitrov',
  'Guido Pella',
  'Guillermo Garcia Lopez',
  'Henri Laaksonen',
  'Holger Rune',
  'Horacio Zeballos',
  'Hubert Hurkacz',
  'Hugo Dellien',
  'Hugo Gaston',
  'Hyeon Chung',
  'Illya Marchenko',
  'Ilya Ivashka',
  'Ivo Karlovic',
  'J J Wolf',
  'Jack Sock',
  'James Duckworth',
  'Jan Lennard Struff',
  'Janko Tipsarevic',
  'Jannik Sinner',
  'Jared Donaldson',
  'Jaume Munar',
  'Jenson Brooksby',
  'Jeremy Chardy',
  'Jerzy Janowicz',
  'Jiri Lehecka',
  'Jiri Vesely',
  'Jo-Wilfried Tsonga',
  'Joao Sousa',
  'John Isner',
  'John Millman',
  'Jordan Thompson',
  'Jozef Kovalik',
  'Juan Ignacio Londero',
  'Juan Martin del Potro',
  'Juan Monaco',
  'Julien Benneteau',
  'Kamil Majchrzak',
  'Karen Khachanov',
  'Kei Nishikori',
  'Kevin Anderson',
  'Kyle Edmund',
  'Laslo Djere',
  'Leonardo Mayer',
  'Lloyd Harris',
  'Lorenzo Musetti',
  'Lorenzo Sonego',
  'Lucas Pouille',
  'Lukas Lacko',
  'Lukas Rosol',
  'Mackenzie Mcdonald',
  'Malek Jaziri',
  'Marc Andrea Huesler',
  'Marcel Granollers',
  'Marco Cecchinato',
  'Marcos Baghdatis',
  'Marcos Giron',
  'Marin Cilic',
  'Marius Copil',
  'Martin Klizan',
  'Marton Fucsovics',
  'Matteo Berrettini',
  'Matthew Ebden',
  'Maxime Cressy',
  'Maximilian Marterer',
  'Mikael Ymer',
  'Mikhail Kukushkin',
  'Mikhail Youzhny',
  'Milos Raonic',
  'Miomir Kecmanovic',
  'Mirza Basic',
  'Mischa Zverev',
  'Nick Kyrgios',
  'Nicolas Almagro',
  'Nicolas Jarry',
  'Nicolas Mahut',
  'Nikoloz Basilashvili',
  'Norbert Gombos',
  'Novak Djokovic',
  'Oscar Otte',
  'Pablo Andujar',
  'Pablo Carreno Busta',
  'Pablo Cuevas',
  'Paolo Lorenzi',
  'Paul Henri Mathieu',
  'Pedro Martinez',
  'Peter Gojowczyk',
  'Philipp Kohlschreiber',
  'Pierre Hugues Herbert',
  'Quentin Halys',
  'Radu Albot',
  'Rafael Nadal',
  'Ramkumar Ramanathan',
  'Reilly Opelka',
  'Renzo Olivo',
  'Ricardas Berankis',
  'Richard Gasquet',
  'Roberto Bautista Agut',
  'Roberto Carballes Baena',
  'Robin Haase',
  'Roger Federer',
  'Rogerio Dutra Silva',
  'Ruben Bemelmans',
  'Ryan Harrison',
  'Salvatore Caruso',
  'Sam Groth',
  'Sam Querrey',
  'Santiago Giraldo',
  'Sebastian Baez',
  'Sebastian Korda',
  'Sergiy Stakhovsky',
  'Simone Bolelli',
  'Soon Woo Kwon',
  'Stan Wawrinka',
  'Stefano Travaglia',
  'Stefanos Tsitsipas',
  'Stephane Robert',
  'Steve Darcis',
  'Steve Johnson',
  'Tallon Griekspoor',
  'Taro Daniel',
  'Taylor Fritz',
  'Tennys Sandgren',
  'Teymuraz Gabashvili',
  'Thanasi Kokkinakis',
  'Thiago Monteiro',
  'Thomas Fabbiano',
  'Thomaz Bellucci',
  'Tim Smyczek',
  'Tomas Berdych',
  'Tommy Paul',
  'Tommy Robredo',
  'Ugo Humbert',
  'Vasek Pospisil',
  'Victor Estrella',
  'Viktor Troicki',
  'Yannick Hanfmann',
  'Yen Hsun Lu',
  'Yoshihito Nishioka',
  'Yuichi Sugita'
];
final List<String> surfaces = ["Hard", "Clay", "Grass", "Carpet"];

String player1 = "Rafael Nadal";
String player2 = "Novak Djokovic";
String surface = "Hard";

String pressedSurface = "Hard";
String pressedPlayer1 = "Rafael Nadal";
String pressedPlayer2 = "Novak Djokovic";

String winner = "Novak Djokovic";
int percentage = 63;

String urlPlayer1 = "Rafael+Nadal";
String urlPlayer2 = "Novak+Djokovic";
String url =
    "http://mltennis.pythonanywhere.com/api?player1=Rafael+Nadal&player2=Novak+Djokovic&surface=Hard";
var data;
var decoded;

Future<void> getJson() async {
  data = await fetchData(url);
  decoded = jsonDecode(data);
}
